### ISSUE TITLE
Does serialization of custom type  need to implement "introspect"?

### ISSUE THREAD

**Issue by dbsxdbsx** [avl/savefile#23]
I am using  savefile 0.8.3 on win10. With the official [example](https://docs.rs/savefile/0.8.3/savefile/index.html), I modified a little like this:

```rust
use std::collections::VecDeque;

use savefile::prelude::*;
#[macro_use]
extern crate savefile_derive;
pub struct MyPathBuf {
    path: String,
}

use savefile::prelude::*;
impl WithSchema for MyPathBuf {
    fn schema(_version: u32) -> Schema {
        Schema::Primitive(SchemaPrimitive::schema_string)
    }
}
impl Serialize for MyPathBuf {
    fn serialize<'a>(&self, serializer: &mut Serializer<'a>) -> Result<(), SavefileError> {
        self.path.serialize(serializer)
    }
}
impl Deserialize for MyPathBuf {
    fn deserialize(deserializer: &mut Deserializer) -> Result<Self, SavefileError> {
        Ok(MyPathBuf {
            path: String::deserialize(deserializer)?,
        })
    }
}

#[derive(Savefile)]
struct Player {
    name: String,
    strength: u32,
    inventory: VecDeque<MyPathBuf>, //Vec<String>,
}

fn main() {
    let player = Player {
        name: "Steve".to_string(),
        strength: 42,
        // inventory: Vec::with_capacity(100),
        inventory: VecDeque::with_capacity(100),
    };
}
```
But it raised error like --- `the trait bound `MyPathBuf: Introspect` is not satisfied
required because of the requirements on the impl of `Introspect` for `VecDeque<MyPathBuf>`
required for the cast to the object type `dyn Introspect``

Does  it mean I need to  implement "introspect"? If so , how?

**Comment by avl** [comment]
Thanks for getting in touch!

You need to add #[derive(Savefile)] before "pub struct MyPathBuf". Then it should work.

**Comment by dbsxdbsx** [comment]
@avl , thanks for your replay.  It is solved with your advice.  And now I have another question:
```rust
#[derive(Savefile)]
pub struct Step {
    pub obs: Tensor,//custom type, raise error say trait Serialze not implemented
    pub priority: f32,
}

struct Player {
    name: String,
    strength: u32,
    inventory: VecDeque<Step>, //Vec<String>,
}

fn main() {
    let player = Player {
        name: "Steve".to_string(),
        strength: 42,
        // inventory: Vec::with_capacity(100),
        inventory: VecDeque::with_capacity(100),
    };
}
```
With this code, if a field is of a custom type from another crate, how to work it out? Is it necessary to call the author to change the type?

**Comment by avl** [comment]
Excellent question! This is a challenge to all crates which require a datatype to implement a specific trait.

There are only two places where the Savefile-traits could be implemented for the Tensor type: 

1: In savefile itself
2: In whichever crate Tensor belongs

This means there are three possible approaches to solving your problem.

1: Add support for Tensor in savefile. I'd be open to this, but I do not have time to implement it, so someone else would have to write a PR. Most likely such a feature should be behind a non-default feature of Savefile.

2: Add support for savefile in Tensor's crate.

3: Wrap the tensor type in a small wrapper just to implement the Savefile-traits. Your 'Step' struct would then look something like this:

```rust
pub struct TensorWrapper(pub Tensor);

#[derive(Savefile)]
pub struct Step {
    pub obs: TensorWrapper,
    pub priority: f32,
}

impl TensorWrapper for Tensor {
 ...implementation here..
}


```

The last solution has the disadvantage of requiring the user to type "my_step.obs.0.whatever" instead of "my_step.obs.whatever".

**Comment by dbsxdbsx** [comment]
@avl , thanks for reply.  I would prefer the 2ed approach.  In addition, there maybe another workaround without modifying crate code---just creating another "shaddow" field with inner typer which contains all data for the custom type. Then when saving or loading, just dealing with all fields except for the custom type,  and the then afterwards rebuilding the custom type filed with the "shaddow" field.

**Comment by avl** [comment]
I just realized that I didn't read your initial post even nearly close enough. I now see that you were trying to derive the Savefile-traits. I think I may have an example which does this, but which does not include the Introspect trait.

You can either implement Introspect, or live without it and instruct the Dervive-macro for Player not to try and derive Introspect for the inventory type. This can be done by using the #[savefile_introspect_ignore] attribute on the inventory field.
