### ISSUE TITLE
No impl (for WithSchema, etc) on char!

### ISSUE THREAD

**Issue by ctrlcctrlv** [avl/savefile#30]
I will PR.

**Comment by avl** [comment]
Solved in commit be8474e2564e688fe1538057e4883be4f8933fb1

**Comment by ctrlcctrlv** [comment]
Thanks a lot :-) Sorry I didn't finish my patch, I was trying too hard to make it three bytes because technically that's all that's needed, haha.

**Comment by ctrlcctrlv** [comment]
(So I was trying to figure out how to avoid an unsafe cast and then decided to think about it later.)

**Comment by avl** [comment]
Oh, you're right! That's clever!

That would, however, mean that it couldn't implement the Savefile ReprC-trait, which would mean structs containing 'char'  couldn't be serialized by just raw binary copy.

Would it have been better for your usecase to have char serialize to 3 bytes?

**Comment by ctrlcctrlv** [comment]
No, it wouldn't have made any difference at all except minor filesize decrease and bragging rights :joy:
