### ISSUE TITLE
Support `#[derive(Savefile)]` on structs with unconstrained generic parameters

### ISSUE THREAD

**Issue by FireFragment** [avl/savefile#31]
The following code:

```rust
#[derive(Savefile)]
struct Foo<T> {
    pub bar: T
}
```

yields errors, that T doesn't implement `Serialize`, `Deserialize`, etc., but this should be possible - implementation, that works only when T fulfills the constraints should be derived.

Eg. in following code:

```rust
#[derive(Clone)]
struct Foo<T> {
    pub bar: T
}
```

`Clone` derive macro generates this implementation: `impl<T: core::clone::Clone> core::clone::Clone for Foo<T> { /*... */}` where T is constrained in the implementation instead of erroring out. Savefile derive macro should behave similarly.

# Benefits

 - There are lots of traits, that must be implemented, so the constraints are a lot of boilerplate. The need for them would be removed
 - Possibility to use some of the Savefile-derived structs with generic arguments, that cannot be _"savefiled"_ in cases one doesn't intend to save it to a file, while other times, one might want to use the same generic struct with  _"savefilable"_ generic arguments and save it to a file

**Comment by avl** [comment]
Thank you very much for this request.

I agree with you on all points!

This should definitely be fixed.

I'll see if I can get it fixed tomorrow.

**Comment by avl** [comment]
The proposed change has been implemented! Happy to hear any feedback!
