### ISSUE TITLE
Request: savefile-derive as a feature flag for savefile

### ISSUE THREAD

**Issue by SandaruKasa** [avl/savefile#35]
Removes the need to keep two versions in a `Cargo.toml` in sync.

See https://github.com/clap-rs/clap/blob/ca855c651c4fbd89accc40b20d442967f1e79942/Cargo.toml#L89

**Comment by avl** [comment]
Thank you for getting in touch!

Is the idea that we introduce a feature flag that can be used to automatically pull in the correct version of savefile_derive, and then re-export the savefile_derive-macros from the savefile crate?

Sounds like a good idea. I'll take a look.

**Comment by avl** [comment]
The feature flag has been added, and shipped in savefile 0.16.2.

Just reopen this or write a new bug if you have further suggestions!

**Comment by SandaruKasa** [comment]
Thank you a lot!
