### ISSUE TITLE
request: support for BTreeSet

### ISSUE THREAD

**Issue by LeHuman** [avl/savefile#64]
Support for the std BTreeSet type would be nice.

As an example, the following fails to compile.

```rust
#[derive(Savefile)]
struct Data {
    data: std::collections::BTreeSet<u32>,
}
```
Thanks!

**Comment by avl** [comment]
Good idea!

I'll get that implemented soon!

**Comment by avl** [comment]
A PR exists now:
https://github.com/avl/savefile/pull/65

I'll get it merged today.

**Comment by avl** [comment]
BTreeSet-support has been merged.
