### ISSUE TITLE
Encryption?

### ISSUE THREAD

**Issue by volfco** [avl/savefile#9]
Any thoughts on adding an encryption layer? I'm not thinking anything fancy, just simple symmetrical encryption with a preshared key. 

I'm inquiring because I'm going to try to use this for state dumps of my applications (and in the future use this to transfer data between applications and datacenters) and encryption natively would remove complexity from my future plans.

Something like this (assuming your demo code):
```
save_encrypted_file("save.bin", 0, player, "my symmetrical key is this").unwrap();
```

**Comment by avl** [comment]
Hi, I've now implemented what you asked for, as I interpreted it! :-)

I'm not entirely convinced encryption functions really belong in a serialization crate, but I agree that it could be convenient and I thought it would be a fun thing to implement.

Savefile now adds the encryption-library 'ring' to its dependencies.

It is published on crates.io now, look for version 0.3.1 .

Have a nice day!
